cloudflare_api_token: ENC[AES256_GCM,data:R5ii1Fq6Ng8z44GjpLHDRtB0p813fth5CiiEmx/rNURxVHgXazh7Cg==,iv:owhiMP28c6aDYXk7a7b/k0brXCnYxH5SSZBpwXB3NpM=,tag:pkwPJmxbSz6Gnkn03xiSpg==,type:str]
cloudflare_r2_secret_access_key: ENC[AES256_GCM,data:bIKD7CjDzHSb5T0Vfjg888+U7Jw+3HUYag1udKhCBA7n2aLSRfG7d0dknJtwhdBW8UaATrYIEw66F4/PSbwezw==,iv:GJYi8aYJEZZ6OL1W1huKyW4VwckW3z2PZK4lAg8qGU8=,tag:OKrpQ4DjfLV7YlJ3+lMI+Q==,type:str]
neon_api_token: ENC[AES256_GCM,data:M0W5/ZwwjDbRjtdhZ1/GjJFuluiNrSHGzT8lGs8na+c0+dPZ/dN9twMaxn7fNH5U2QVxNMVMi/4lgzgdXVg5lDW8qDA9,iv:Mo2qUca/U4FeM63Up1vu52PSCN2MSd9U0Vt4d9yj6dI=,tag:aII2su+kFvalWJV2NAiWfA==,type:str]
smtp_password: ENC[AES256_GCM,data:1wj5fU5sUTxM3JRg/RhkmziW3rT3BJ1s+6lvEaBnb3qzSFYpMA==,iv:qQwOkhFUOJZ7q/lXeFDMPEfz7U7tiCgq8+ei4UYzzss=,tag:DZu/TT+AihIpA8ed4w6Ouw==,type:str]
smtp_username: ENC[AES256_GCM,data:7hrzYR+q5HA5wA9JJG47P0gkpj6E,iv:vZWZjnmC8VGJhKCQZ5+jdadt+t4SIQtR3vy4pDEISOk=,tag:m47IW7zy5RIbq40XnfUDgw==,type:str]
cloudflare_api_token_for_server_worker: ENC[AES256_GCM,data:p3+zMEWhEGqEQjrw42DgP27s31uNkCerupFjjFwjDMCGiuYgDp6sGw==,iv:LjoK2EllHwlBpM/nHUURgDCn+mGT+zlfB6DnFhCD4oE=,tag:wLBt5AxkTLhnVUUarycNfQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7uD0e1fPbqpER1d7CM3EWEnMHlkLNzCfI4NK/Qs+/K
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFR5YkltdyBtNkV4
            V2JnbUpPRk5idjgzUXNQVDJibGRXNUlMUFpCbnl4VmpHRnVtaFJjCjN0ZG9pN292
            cklNSmdvc0tmKzk4UDNRZkdHNDgxVG1NWWtGN01hRmlKT1UKLS0tIHBKbEVmclVz
            NEZnT3Q0eXpPbCtMNWk0YWkySXZveGd5cXE2YTdDSGw3bzAKrtBiWKpwO2qqyZxn
            VI90vpP7wAd6fHsvfmIUyiAP0gHOtNpBSS6DlKQkUZO9Y2Er/WHqV3FM+scM7nV9
            2aTvpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-29T19:43:56Z"
    mac: ENC[AES256_GCM,data:NpOAnXEKOBc+4NL7Cjj1843oqmYxafkFpVwpx4hzEp7V4cFx7TmxYrSNSjcz5+lfvbjm1mW1t5nxYHwFU8p9XaMuS0DbPqsgr6Cx2CvMR01vcBwpPCjkrQsQ/u2dRlwovb8yf/QDOeaCmWAgMRIcrcY49BKADKD0hcLJZoGQY0I=,iv:FarUR+CQjU6lmdFgR3n/J6hhECd/cS6vUGa0+GearS8=,tag:qk9uLhffliTKrqTfLQ2fbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
