advisory_stage_admins:
    prod:
        - ENC[AES256_GCM,data:o8h1Zg7hcI3smLyriA==,iv:byaCGst1ppP1+vBHmriDjz9PMqMZSPpariyzXECJA1o=,tag:kdUa7uH0tkO2C2rC81Kr7Q==,type:str]
    test:
        - ENC[AES256_GCM,data:/sjwtlxalstH3yUkyw==,iv:vK8i/U2VqUwu9essePCul4otCRWRrai2Vuwbeu8UIE4=,tag:hRhdo05tuC6PSyPaeacP8g==,type:str]
advisory_tofu_admins:
    - ENC[AES256_GCM,data:IWWEW6mlP+nEZOJTSA==,iv:HB/HMaE377UoQJA83XUzTRSYGnVfFUSjssWMYkDh4sY=,tag:VEdb9gPRoGQ/W6c96qRMyQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7uD0e1fPbqpER1d7CM3EWEnMHlkLNzCfI4NK/Qs+/K
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFR5YkltdyB4MitG
            UWJXUEMrdG1nWlF2WFRuWFF6SnAzeERKMGViV0NIUDN3NVAyYkNRCm5tM1FIV3B1
            NUNQOGJ0MWFvbVZlSEllUVpMUlB4RHVEOWthL3AzMnZvL3cKLS0tIFhGVDc4dHJh
            MlROUTR6ektqNHVPa1FMQmdPWXkvbmRQci95YU5GYVpZL2sK7D+Vi0qIQQDWH11T
            kW6G4teHJiwis5jMaj5KM6VGyQ8pCNDO3sKaB+xYRAR6UBz1iLcFrUdd6R7eSsrb
            wyeafg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T18:10:53Z"
    mac: ENC[AES256_GCM,data:MOuZrgFiXonvEhtHneKemeU7a+U+zV/u9pd4KkDiZiZLOU6WC5JUiigmNXaQFz55yLqFccuF7fMfTmmXHn2ugSOHKDEC+lVRNDNNsf8SwGJyrhv1au3920vL28YpFaEmzHeILMTvoJb0jTnQyTBR4bAA+9Z0ODzOO1ZhhBM8OwA=,iv:XLrrFy95oS9J90lWBvcsPwHvu4yD+c7mJ3OQjXR7LlA=,tag:MzwOtZlUfbHYPiO6P/u9EA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
