advisory_stage_admins:
  prod:
    - ENC[AES256_GCM,data:o8h1Zg7hcI3smLyriA==,iv:byaCGst1ppP1+vBHmriDjz9PMqMZSPpariyzXECJA1o=,tag:kdUa7uH0tkO2C2rC81Kr7Q==,type:str]
  test:
    - ENC[AES256_GCM,data:/sjwtlxalstH3yUkyw==,iv:vK8i/U2VqUwu9essePCul4otCRWRrai2Vuwbeu8UIE4=,tag:hRhdo05tuC6PSyPaeacP8g==,type:str]
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ7uD0e1fPbqpER1d7CM3EWEnMHlkLNzCfI4NK/Qs+/K
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFR5YkltdyB4MitG
        UWJXUEMrdG1nWlF2WFRuWFF6SnAzeERKMGViV0NIUDN3NVAyYkNRCm5tM1FIV3B1
        NUNQOGJ0MWFvbVZlSEllUVpMUlB4RHVEOWthL3AzMnZvL3cKLS0tIFhGVDc4dHJh
        MlROUTR6ektqNHVPa1FMQmdPWXkvbmRQci95YU5GYVpZL2sK7D+Vi0qIQQDWH11T
        kW6G4teHJiwis5jMaj5KM6VGyQ8pCNDO3sKaB+xYRAR6UBz1iLcFrUdd6R7eSsrb
        wyeafg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T16:27:56Z"
  mac: ENC[AES256_GCM,data:vJ4sw/bVADIvW0L0giAO1o+e5njBuKfPsILTBg3kJChoka5HcuvbgsKPbOUeL0OczFk3WqtcowYtodako/CPhfxslGQPj1pL10r4GBDFvcfYPznDe7scCMD3CdYcLh4nLCZwByqH3eMzRH+ORFi6pfEidiXgEvPISTPAwK9m61U=,iv:okI763SojBfn5L2nc2ATMc19HOUTizPyDBv/FCr//mE=,tag:Rt3sN3GOIzunuYHUf26bHQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
